### ISSUE TITLE
New Kindle Oasis - Tinderizer stopped working

### ISSUE THREAD

**Issue by CNJH** [darkhelmet/tinderizer#1]
Hi. I recently bought a new Kindle Oasis and Tinderizer doesn't seem to want to send articles to it from my bookmarklet. I've tried setting it up again, and set the Oasis as my default Kindle, but the articles still don't seem to be arriving. Any ideas?
Thanks!
Been using the app for years now - it is SO handy!

**Comment by darkhelmet** [comment]
Did you create a new bookmarklet with the new email that goes to you Oasis? It's not really about which device is the default, they each have their own email address.

**Comment by CNJH** [comment]
Thank you. I've sorted it.
Your app is amazing. Couln't do without it.

**Comment by CNJH** [comment]
Gutted to get this from Amazon today…
Is there anything I can do to keep using your app?

**Comment by darkhelmet** [comment]
What did you get from Amazon? I'm not seeing anything.

**Comment by CNJH** [comment]
﻿
How strange. Sorry - I thought I’d attached a screenshot. Here is their email to me, pasted:

Dear Kindle Customer,

Thank you for using the Send to Kindle service to send personal documents to your Kindle library. We noticed that the following document(s), sent by you at 06:13 PM on Tue, Jun 21, 2022 GMT are in MOBI (.mobi, .azw) formats:
* Tinderizer.mobi


We wanted to let you know that starting August 2022, you’ll no longer be able to send MOBI (.mobi, .azw) files to your Kindle library. Any MOBI files that are already in your library will not be affected by this change. MOBI is an older file format and won’t support the newest Kindle features for documents. Any existing MOBI files that you want to read with our most up-to-date features for documents will need to be re-sent in a compatible format.

Compatible formats now include EPUB (.epub), which you can send to your library using your Send to Kindle email address. We’ll also be adding EPUB support to the free Kindle app for iOS and Android devices and the Send to Kindle desktop app for PC and Mac.      

 If you have any questions, please visit our help page or contact our Customer Service team.      

 Regards,
Amazon Kindle Support

**Comment by darkhelmet** [comment]
Yeah, those happen randomly, I have never figured out why. Sometimes they happen on pages that should work, but then I try the same page and it sends properly to me. No idea.

**Comment by CNJH** [comment]
﻿
Oh, good. 
So this isn’t anything to worry about? Would hate not to be able to use Tinderizer!

“We wanted to let you know that starting August 2022, you'll no longer be able to send MOBI (.mobi,
azw) files to your Kindle library”

Thanks for your help.

**Comment by darkhelmet** [comment]
Oh, shoot I missed that part...well I guess this might be the end of Tinderizer...

I use a tool provided by Amazon in the conversion process to convert the file into the format the Kindle will read. They don't support that tool anymore, and honestly I don't have the capacity or desire to try to find a replacement to convert to EPUB in a way that is required to make it work.

So yeah...this might be the end.

**Comment by CNJH** [comment]
Ach that’s such a shame. 
I’ll miss it so much. 
It was good while it lasted. 
Farewell Tinderizer.

**Comment by walterhenrique** [comment]
I'm here just to thanks a lot to Darkhelmet because my life were better when I was using Tinderizer.
I know that it does not work anymore, but that project changed my life and I just wanted to thank u.
TKS TKS TKS !!!!
