### ISSUE TITLE
MOBI filetype wont be supported anymore

### ISSUE THREAD

**Issue by walterhenrique** [darkhelmet/tinderizer#2]
Hi. I love the tinderizer "send to my Kindle" project. I have two Kindle and I use tinderizer bookmarklet in both.
But. I'm afraid.
I'm brazilian. And I received a message from **Amazon that says the MOBI filetype wont be supported since 2022 august**.
And the JS code from you pack the website text exactly in that format.

I would like to know what you will do to keep the service running, if you can, of course.

##Thanks to attention.

**Comment by darkhelmet** [comment]
Yes, I've seen that message too. Amazon stopped supporting the tool I use to do the final conversion, and I don't have the time or desire to look into a replacement. This might just be the end of Tinderizer.
